---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blue-green
  namespace: argocd
spec:
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: blue-green
    repoURL: https://github.com/wafflemaester/argocd-example-apps
  syncPolicy:
    automated: {}
